package com.jhuep.web_development.pizzapolis.entity;
// Generated May 9, 2017 4:30:58 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * OrderSummary generated by hbm2java
 */
public class OrderSummary implements java.io.Serializable {

    private Integer id;
    private Customer customer;
    private Date date;
    private Double totalCost;
    private Set<OrderSides> orderSideses = new HashSet<OrderSides>(0);
    private Set<OrderPizza> orderPizzas = new HashSet<OrderPizza>(0);

    public OrderSummary() {
    }

    public OrderSummary(Customer customer, Date date, Double totalCost, Set<OrderSides> orderSideses, Set<OrderPizza> orderPizzas) {
        this.customer = customer;
        this.date = date;
        this.totalCost = totalCost;
        this.orderSideses = orderSideses;
        this.orderPizzas = orderPizzas;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Customer getCustomer() {
        return this.customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public Double getTotalCost() {
        return this.totalCost;
    }

    public void setTotalCost(Double totalCost) {
        this.totalCost = totalCost;
    }

    public Set<OrderSides> getOrderSideses() {
        return this.orderSideses;
    }

    public void setOrderSideses(Set<OrderSides> orderSideses) {
        this.orderSideses = orderSideses;
    }

    public Set<OrderPizza> getOrderPizzas() {
        return this.orderPizzas;
    }

    public void setOrderPizzas(Set<OrderPizza> orderPizzas) {
        this.orderPizzas = orderPizzas;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 89 * hash + Objects.hashCode(this.customer);
        hash = 89 * hash + Objects.hashCode(this.date);
        hash = 89 * hash + Objects.hashCode(this.totalCost);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final OrderSummary other = (OrderSummary) obj;
        if (!Objects.equals(this.customer, other.customer)) {
            return false;
        }
        if (!Objects.equals(this.date, other.date)) {
            return false;
        }
        if (!Objects.equals(this.totalCost, other.totalCost)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "OrderSummary{" + "id=" + id + ", customer=" + customer + ", date=" + date + ", totalCost=" + totalCost + '}';
    }

}
