package com.jhuep.web_development.pizzapolis.entity;
// Generated May 9, 2017 4:30:58 PM by Hibernate Tools 4.3.1

import java.util.Objects;

/**
 * OrderSides generated by hbm2java
 */
public class OrderSides implements java.io.Serializable {

    private Integer id;
    private OrderSummary orderSummary;
    private Sides sides;
    private Integer quantity;

    public OrderSides() {
    }

    public OrderSides(OrderSummary orderSummary, Sides sides) {
        this.orderSummary = orderSummary;
        this.sides = sides;
    }

    public OrderSides(OrderSummary orderSummary, Sides sides, Integer quantity) {
        this.orderSummary = orderSummary;
        this.sides = sides;
        this.quantity = quantity;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public OrderSummary getOrderSummary() {
        return this.orderSummary;
    }

    public void setOrderSummary(OrderSummary orderSummary) {
        this.orderSummary = orderSummary;
    }

    public Sides getSides() {
        return this.sides;
    }

    public void setSides(Sides sides) {
        this.sides = sides;
    }

    public Integer getQuantity() {
        return this.quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 19 * hash + Objects.hashCode(this.orderSummary);
        hash = 19 * hash + Objects.hashCode(this.sides);
        hash = 19 * hash + Objects.hashCode(this.quantity);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final OrderSides other = (OrderSides) obj;
        if (!Objects.equals(this.orderSummary, other.orderSummary)) {
            return false;
        }
        if (!Objects.equals(this.sides, other.sides)) {
            return false;
        }
        if (!Objects.equals(this.quantity, other.quantity)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "OrderSides{" + "id=" + id + ", orderSummary=" + orderSummary + ", sides=" + sides + ", quantity=" + quantity + '}';
    }

}
