package com.jhuep.web_development.pizzapolis.entity;
// Generated May 9, 2017 4:30:58 PM by Hibernate Tools 4.3.1

import java.util.Objects;

/**
 * OrderPizza generated by hbm2java
 */
public class OrderPizza implements java.io.Serializable {

    private Integer id;
    private OrderSummary orderSummary;
    private Pizza pizza;
    private Integer quantity;

    public OrderPizza() {
    }

    public OrderPizza(OrderSummary orderSummary, Pizza pizza, Integer quantity) {
        this.orderSummary = orderSummary;
        this.pizza = pizza;
        this.quantity = quantity;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public OrderSummary getOrderSummary() {
        return this.orderSummary;
    }

    public void setOrderSummary(OrderSummary orderSummary) {
        this.orderSummary = orderSummary;
    }

    public Pizza getPizza() {
        return this.pizza;
    }

    public void setPizza(Pizza pizza) {
        this.pizza = pizza;
    }

    public Integer getQuantity() {
        return this.quantity;
    }

    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 67 * hash + Objects.hashCode(this.orderSummary);
        hash = 67 * hash + Objects.hashCode(this.pizza);
        hash = 67 * hash + Objects.hashCode(this.quantity);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final OrderPizza other = (OrderPizza) obj;
        if (!Objects.equals(this.orderSummary, other.orderSummary)) {
            return false;
        }
        if (!Objects.equals(this.pizza, other.pizza)) {
            return false;
        }
        if (!Objects.equals(this.quantity, other.quantity)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "OrderPizza{" + "id=" + id + ", orderSummary=" + orderSummary + ", pizza=" + pizza + ", quantity=" + quantity + '}';
    }

}
