package com.jhuep.web_development.pizzapolis.entity;
// Generated May 9, 2017 4:30:58 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * PizzaSauce generated by hbm2java
 */
public class PizzaSauce implements java.io.Serializable {

    private Integer id;
    private String sauceName;
    private Double cost;
    private Set<Pizza> pizzas = new HashSet<Pizza>(0);

    public PizzaSauce() {
    }

    public PizzaSauce(String sauceName, Double cost, Set<Pizza> pizzas) {
        this.sauceName = sauceName;
        this.cost = cost;
        this.pizzas = pizzas;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getSauceName() {
        return this.sauceName;
    }

    public void setSauceName(String sauceName) {
        this.sauceName = sauceName;
    }

    public Double getCost() {
        return this.cost;
    }

    public void setCost(Double cost) {
        this.cost = cost;
    }

    public Set<Pizza> getPizzas() {
        return this.pizzas;
    }

    public void setPizzas(Set<Pizza> pizzas) {
        this.pizzas = pizzas;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 71 * hash + Objects.hashCode(this.sauceName);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final PizzaSauce other = (PizzaSauce) obj;
        if (!Objects.equals(this.sauceName, other.sauceName)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "PizzaSauce{" + "id=" + id + ", sauceName=" + sauceName + ", cost=" + cost + '}';
    }

}
